module.exports = (bot) => {
    ////No borres el module.exports = (bot) => {} //// 
    bot.variables({
        PREFIX: "c",
        prefix: "ch!",
        version: "v1.0.1",
        antispam: "",
        antispamconfig: "off",
        //  aqui pones los IDs de los canales(channel) logs del bot
        channelRemovido: "1013443637914374224",
        channelUnion: "1013443580293042246",
        channelTarifa: "1013443826158931979",
        channelReady: "1013443773549785088",
        channelPremimAgregado: "1013444228556263464",
        channelPremiumRemovido: "1013444289675677789",
        channelErrores: "1013650016260341812",
        channelCalificar: "1013443527226695720",
        ////ticket
        tick_c: "",
        tick: "",
        tick_r: "",
        antiraidlog: "",
        antiraid: "",
        antisay: "false",
        antilogger: "false",
        antirole: "false",
        command: "enabled",
        sisexd: "<:rukatest:958134186579996753>",
        WelcomeChannel: "",
        WelcomeColor: "#F3FFAF",
        WelcomeThumbnail: "$userAvatar[$authorID]",
        WelcomeMessage: "Bienvenido {user.ping} a {server}!",
        WelcomeTitle: "Bienvenido/a {user.tag}",
        LeaveChannel: "",
        LeaveMessage: "{user.ping} se fue de {server}!",
        LeaveTitle: "Adios {user.tag}",
        LeaveColor: "",
        LeaveThumbnail: "$userAvatar[$authorID]",
        warn: "0",
        reason: "",
        ticketid: "",
        ticketcat: "",
        ticketmessage: "",
        ticketafteropenmessage: "",
        ticketsystem1: "x",
        ticketchannelname: "",
        host: "",
        win: "",
        date: "",
        time: "",
        prize: "",
        banmessage: "",
        logchannel: "",
        afk: "false",
        afkr: "No Especificada",
        ////////NEW VARIABLE
        modlogs: "0",
        logs: "",
        rch: "",
        rmsg: "{user.tag}🎉, subiste de nivel ahora eres **{level}**",
        lvl: "0",
        exp: "0",
        rexp: "40",
        rsystem: "0",
        chsug: "0",
        leavechannel: "",
        lmessage: "",
        wchannel: "",
        wmessage: "",
        warn: "",
        warnCount: "0",
        bg: "https://media.discordapp.net/attachments/916451815556534292/942116619826630686/welcome_2.png",
        lbg: "https://cdn.discordapp.com/attachments/916451815556534292/942765441779130448/bye_2.png",
        rolmute: "",
        ccmd: "",
        cdes: "",
        chsug: "",
        Captcha: "",
        /////////////ANTILINKS///////////////////////////
        Warns: "0",
        Total: "0",
        An: "No",
        Conf: "No",
        Pats: "0",
        Hugs: "0",
        Kiss: "0",
        DevLog: "13",
        XP: "0",
        Mute: "No",
        LvlXP: "0",
        Tag: "Ninguno",
        Links: "false",
        Invite: "false",
        black: "false",
        blackCount: "0",
        BBlack: "Ninguno",
        uBBlack: "Ninguno",
        LvlXP2: "0",
        uptime: "0",
        desc: "No hay Descripción!",
        CCount: "15",
        ticketchannel: "",
        
        //////////
        bag: "0",
        DailyChest: "0",
        WeeklyChest: "0",
        spiteful: "0",
        XP: "0",
        rbg: "https://cdn.discordapp.com/attachments/916451815556534292/939322296382939196/rank.png",
        encuesta: "",
        /////////////BLACKLIST//////////
        numblacklist: "0",
        lastblacklist: "Nadie",
        rblacklist: "",
        Blacklist: "false",
        blacklist: "false",
        lastunblacklist: "Nadie",
        /////////////////////////AFK///////////////
        Total: "0",
        Roulette: "",
        An: "No",
        Conf: "No",
        Pats: "0",
        Hugs: "0",
        Kiss: "0",
        DevLog: "13",
        XP: "0",
        Mute: "No",
        LvlXP: "0",
        Tag: "Ninguno",
        Links: "false",
        black: "false",
        blackCount: "0",
        BBlack: "Ninguno",
        uBBlack: "Ninguno",
        LvlXP2: "0",
        uptime: "0",
        BotToken: "$clientToken",
        desc: "No hay Descripción!",
        botinv: "",
        CCount: "16",
        Premium: "false",
    });
}

/*
╔═════════════════════════════════════════════════════╗
║|| - || Desarrollado por Carlos Ghozd#2653 || - ||   ║
║   ----------| discord.io/chocomara |----------      ║
╚═════════════════════════════════════════════════════╝
*/